:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

= RHEL 8 New Features workshop - Latam Tech Office Workshop series

:numbered:

== Description

This workshop is aimed to show to customers and partners the main features of RHEL 8 in a very dynamic and inmmersive way. 

We have three main dynamisc in each feature showed.

* Theory with Whiteboarding
* Practice in a RHEL instance
* Discussion of the feature in a real world use case

Duration: 3.5h

Audience: IT Managers, Architects and technical staff who operates Linux

== Application Streams

=== Description

With the introduction of Red Hat Enterprise Linux 8 (RHEL 8) Red Had has tried to greatly simplify the layout of the content available in Red Hat Enterprise Linux. The main repository, BaseOS, provides the parts of the distribution that give you a running user space on physical hardware, a virtual machine, a cloud instance or a container. The Application Stream (AppStreams) repository provides all the applications you might want to run in a given userspace. The Supplemental repository provides other software that has special licensing. 

=== Whiteboarding

Use a whiteboard to explain how base os and appstreams are separated and how this helps to have better control and maintainability of kernel and user spaces.

=== Pre Execution

Use a whiteboard to explain how base os and appstreams are separated and how this helps to have better control and maintainability of kernel and user spaces.
Execution

*Show the repos*

[source, bash]
------------------
# sudo yum repolist
# sudo subscription-manager repos --list-enabled
------------------

*Enable or disable repos*

[source, bash]
------------------
# sudo subscription-manager repos --disable=repoID
# sudo subscription-manager repos --enable=repoID
------------------

*Show the modules available*

[source, bash]
------------------
# sudo yum module list
------------------

*Example installing python 2.7 along with python 3.6*

[source, bash]
------------------
# sudo yum module info python27
# sudo yum module install python27
------------------

*Other example installing nodejs*

[source, bash]
------------------
# yum module install nodejs:8/development
# yum module enable nodejs
# yum module disable nodejs
# yum module remove nodejs:8/minimal
------------------

=== Post Execution

Get from customer insight and feedback of how they could use this kind of features in their day by day operation, looking for real cases to be implemented. Stimulate a conversation of max 5 minutes relating to this topic.

=== Additional recommended exercises for the customer

*Install postgresql 9.6* 

[source, bash]
------------------
# yum module disable postgresql
# yum module install postgresql:9.6
# yum module list
------------------

*Now switch to version 10.0*

[source, bash]
------------------
# yum module disable postgresql
# yum module install postgresql:10/client
# yum module list
------------------

== WEB CONSOLE

=== Description

The Red Hat Enterprise Linux web console is an open source project called Cockpit that provides a user-friendly web interface allowing for the remote administration of servers. Starting with Red Hat Enterprise Linux 7, the cockpit package provides a powerful and extensible web console for system administration.

=== Pre Execution

Use a whiteboard to explain how web console could help to rhel administration. Explain the modularity and extensibility of the tool. 

Explain for what these plugins could be used for.

* cockpit-composer
* cockpit-pcp
* cockpit-dashboard
* cockpit-machines
* cockpit-session-recording

=== Execution

*Enabling repositories  in RHEL 7*

[source, bash]
------------------
# subscription-manager repos --enable=rhel-7-server-extras-rpms
# subscription-manager repos --enable=rhel-7-server-optional-rpms
------------------

*Installation*

[source, bash]
------------------
# yum install cockpit cockpit-dashboard
------------------

*Enabling cockpit*

[source, bash]
------------------
# firewall-cmd --add-port=9090/tcp
# firewall-cmd --add-port=9090/tcp --permanent 
# systemctl enable cockpit.socket
# systemctl start cockpit.socket
------------------

Show the tool explaining every aspect of web console accessing it at https://host_ip:9090

=== Post Execution

Get from customer insight and feedback of how they could use this kind of features in their day by day operation, looking for real cases to be implemented. Stimulate a conversation of max 5 minutes relating to this topic.

A good next step is (from a customer perspective) creating a RHEL 8 VM to centralized cockpit using cockpit-dashboard and manage all other servers RHEL 7.4 and above and 8 servers.

=== Additional recommended exercises for the customer

Access Web Console and execute the following steps
Create a Raid 1 volume with 2x8GB disks configured in the VM
Select the volume and format it with XFS and a define a mount point
Mount the newly created volume
Access the terminal from from web Console

[source, bash]
------------------
# lvm
# lsblk
# df -kh
------------------

== SESSION RECORDINGS

=== Description

The session recording solution is provided within Red Hat Enterprise Linux 8 and it is based on the tlog package. The tlog package and its associated web console session player provide you with the ability to record and playback user terminal sessions. You can configure the recording to take place per user or user group via the SSSD service. All terminal input and output is captured and stored in a text-based format in the system journal.

=== Pre Execution

Use a whiteboard to explain for what session recordings can be used. Make customer understand how tlog and SSSD comes into play and the formats in which the sessions are recorded.

=== Execution

*Installation*

[source, bash]
------------------
# yum install tlog
#  yum install cockpit-session-recording
# systemctl start cockpit.socket
# systemctl enable cockpit.socket --now
------------------

Using SSSD to control what sessions to record

Modify sssd-session-recording.conf file

[source, bash]
------------------
vi /etc/sssd/conf.d/sssd-session-recording.conf
------------------

Look for [session_recording]
scope = some 
users = example1, example2
groups = examples
Scope could be none | some | all

*Exercise*

* Using Web Console create a user called recording then log-in with that account
* Modify using gui or file with scope some the users with recording
* See the little byte video to see how to conduct the demonstration from now on.

Optional: Exporting recorded sessions to a file

[source, bash]
------------------
# yum install systemd-journal-remote
# journalctl -o export | systemd-journal-remote -o /tmp/dir/example.journal -
------------------

Optional: playing back the session using tlog-play

Find out the session id

[source, bash]
------------------
# journalctl -o verbose | grep -i \”rec\”
# tlog-play -r journal -M TLOG_REC=<number>
------------------

=== Post Execution

Get from customer insight and feedback of how they could use this kind of features in their day by day operation, looking for real cases to be implemented. Stimulate a conversation of max 5 minutes relating to this topic.

Other actions could involve security and remediation groups for showing how session recordings could help to auditories, forensic, documentation and education.

== VIRTUAL DATA OPTIMIZER

=== Description

Virtual Data Optimizer (VDO) provides inline data reduction for Linux in the form of deduplication, compression, and thin provisioning. When you set up a VDO volume, you specify a block device on which to construct your VDO volume and the amount of logical storage you plan to present.




