:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

= RHEL 8 New Features workshop - Latam Tech Office Workshop series

:numbered:

== Description

This workshop is aimed to show to customers and partners the main features of RHEL 8 in a very dynamic and inmmersive way. 

We have three main dynamisc in each feature showed.

* Theory with Whiteboarding
* Practice in a RHEL instance
* Discussion of the feature in a real world use case

Duration: 3.5h

Audience: IT Managers, Architects and technical staff who operates Linux

== Application Streams

=== Description

With the introduction of Red Hat Enterprise Linux 8 (RHEL 8) Red Had has tried to greatly simplify the layout of the content available in Red Hat Enterprise Linux. The main repository, BaseOS, provides the parts of the distribution that give you a running user space on physical hardware, a virtual machine, a cloud instance or a container. The Application Stream (AppStreams) repository provides all the applications you might want to run in a given userspace. The Supplemental repository provides other software that has special licensing. 

=== Whiteboarding

Use a whiteboard to explain how base os and appstreams are separated and how this helps to have better control and maintainability of kernel and user spaces.

=== Pre Execution

Use a whiteboard to explain how base os and appstreams are separated and how this helps to have better control and maintainability of kernel and user spaces.
Execution

*Show the repos*

[source, bash]
------------------
# sudo yum repolist
# sudo subscription-manager repos --list-enabled
------------------

*Enable or disable repos*

[source, bash]
------------------
# sudo subscription-manager repos --disable=repoID
# sudo subscription-manager repos --enable=repoID
------------------

*Show the modules available*

[source, bash]
------------------
# sudo yum module list
------------------

*Example installing python 2.7 along with python 3.6*

[source, bash]
------------------
# sudo yum module info python27
# sudo yum module install python27
------------------

*Other example installing nodejs*

[source, bash]
------------------
# yum module install nodejs:8/development
# yum module enable nodejs
# yum module disable nodejs
# yum module remove nodejs:8/minimal
------------------

=== Post Execution

Get from customer insight and feedback of how they could use this kind of features in their day by day operation, looking for real cases to be implemented. Stimulate a conversation of max 5 minutes relating to this topic.

=== Additional recommended exercises for the customer

*Install postgresql 9.6* 

[source, bash]
------------------
# yum module disable postgresql
# yum module install postgresql:9.6
# yum module list
------------------

*Now switch to version 10.0*

[source, bash]
------------------
# yum module disable postgresql
# yum module install postgresql:10/client
# yum module list
------------------

== WEB CONSOLE

=== Description

The Red Hat Enterprise Linux web console is an open source project called Cockpit that provides a user-friendly web interface allowing for the remote administration of servers. Starting with Red Hat Enterprise Linux 7, the cockpit package provides a powerful and extensible web console for system administration.

=== Pre Execution

Use a whiteboard to explain how web console could help to rhel administration. Explain the modularity and extensibility of the tool. 

Explain for what these plugins could be used for.

* cockpit-composer
* cockpit-pcp
* cockpit-dashboard
* cockpit-machines
* cockpit-session-recording

=== Execution

*Enabling repositories  in RHEL 7*

[source, bash]
------------------
# subscription-manager repos --enable=rhel-7-server-extras-rpms
# subscription-manager repos --enable=rhel-7-server-optional-rpms
------------------

*Installation*

[source, bash]
------------------
# yum install cockpit cockpit-dashboard
------------------

*Enabling cockpit*

[source, bash]
------------------
# firewall-cmd --add-port=9090/tcp
# firewall-cmd --add-port=9090/tcp --permanent 
# systemctl enable cockpit.socket
# systemctl start cockpit.socket
------------------

Show the tool explaining every aspect of web console accessing it at https://host_ip:9090

=== Post Execution

Get from customer insight and feedback of how they could use this kind of features in their day by day operation, looking for real cases to be implemented. Stimulate a conversation of max 5 minutes relating to this topic.

A good next step is (from a customer perspective) creating a RHEL 8 VM to centralized cockpit using cockpit-dashboard and manage all other servers RHEL 7.4 and above and 8 servers.

=== Additional recommended exercises for the customer

Access Web Console and execute the following steps
Create a Raid 1 volume with 2x8GB disks configured in the VM
Select the volume and format it with XFS and a define a mount point
Mount the newly created volume
Access the terminal from from web Console

[source, bash]
------------------
# lvm
# lsblk
# df -kh
------------------

== SESSION RECORDINGS

=== Description

The session recording solution is provided within Red Hat Enterprise Linux 8 and it is based on the tlog package. The tlog package and its associated web console session player provide you with the ability to record and playback user terminal sessions. You can configure the recording to take place per user or user group via the SSSD service. All terminal input and output is captured and stored in a text-based format in the system journal.

=== Pre Execution

Use a whiteboard to explain for what session recordings can be used. Make customer understand how tlog and SSSD comes into play and the formats in which the sessions are recorded.

=== Execution

*Installation*

[source, bash]
------------------
# yum install tlog
#  yum install cockpit-session-recording
# systemctl start cockpit.socket
# systemctl enable cockpit.socket --now
------------------

Using SSSD to control what sessions to record

Modify sssd-session-recording.conf file

[source, bash]
------------------
vi /etc/sssd/conf.d/sssd-session-recording.conf
------------------

Look for [session_recording]
scope = some 
users = example1, example2
groups = examples
Scope could be none | some | all

*Exercise*

* Using Web Console create a user called recording then log-in with that account
* Modify using gui or file with scope some the users with recording
* See the little byte video to see how to conduct the demonstration from now on.

Optional: Exporting recorded sessions to a file

[source, bash]
------------------
# yum install systemd-journal-remote
# journalctl -o export | systemd-journal-remote -o /tmp/dir/example.journal -
------------------

Optional: playing back the session using tlog-play

Find out the session id

[source, bash]
------------------
# journalctl -o verbose | grep -i \”rec\”
# tlog-play -r journal -M TLOG_REC=<number>
------------------

=== Post Execution

Get from customer insight and feedback of how they could use this kind of features in their day by day operation, looking for real cases to be implemented. Stimulate a conversation of max 5 minutes relating to this topic.

Other actions could involve security and remediation groups for showing how session recordings could help to auditories, forensic, documentation and education.

== VIRTUAL DATA OPTIMIZER

=== Description

Virtual Data Optimizer (VDO) provides inline data reduction for Linux in the form of deduplication, compression, and thin provisioning. When you set up a VDO volume, you specify a block device on which to construct your VDO volume and the amount of logical storage you plan to present.

=== Pre Execution

Use a whiteboard to explain how VDO can be used for optimizing volumes, create appliances and talk a little on how the device mapper is in place in the disk architecture for creating other more high level disk structures in which vdo will sit on.

Talk about  the UDS Kernel Module and the VDO Kernel Module as fundamental parts of the service.

Comment on possible use cases like VM and container storing, non structured data, logs consolidation and backups. 

=== Execution

*Installation*

[source, bash]
------------------
# yum install vdo kmod-kvdo
# systemctl start vdo
# systemctl enable vdo
------------------

Using Web Console looking from demonstrating how easy is to create a VDO volume on top of a RAID 1 volume.

* Create a RAID 1 volume using the 2x8GB disks in the VM
* Create a VDO Volume on top of the RAID 1 volume just created
* Create a XFS filesystem on the vdo volume
* Take it to the limit with the following script on the data mount point

[source, bash]
------------------
# while true; do file=`date +'%Y%m%d_%H%M%S_%N'`;  echo $file; journalctl -o verbose >> $file; ps -ef >> $file; done
------------------

* Monitor the utilization

[source, bash]
------------------
# clear; while true; do df -kh; echo ---;sudo vdostats --hu; echo “---”; ls | wc -l; sleep 5; clear; done
------------------

=== Post Execution

Get from customer insight and feedback of how they could use this kind of features in their day by day operation, looking for real cases to be implemented. Stimulate a conversation of max 5 minutes relating to this topic.

What escenarios could be considered for implementing VDO?. Logs Consolidation?. Session Recordings Consolidation?, Backups?.

== IMAGE BUILDER

=== Description

Red Hat Enterprise Linux 8 ships a new tool, called Image Builder, that allows you to create custom Red Hat Enterprise Linux system images in a variety of formats. These include compatibility with major cloud providers and virtualization technologies available in the market. As a result, it enables you to quickly spin up new Red Hat Enterprise Linux (RHEL) systems in different platforms, according to your requirements.

=== Pre Execution

Use a whiteboard to explain how image builder could be helpful to create and maintain rhel images. 

Tell possible scenarios and use cases for creating images and the benefits of using such technology to be more agile in delivering OS.

=== Execution

*Installation* 

[source, bash]
------------------
# yum install lorax-composer composer-cli cockpit-composer bash-completion
# systemctl enable --now lorax-composer.socket
# systemctl enable cockpit.socket (optional)
# firewall-cmd --add-service=cockpit && firewall-cmd --add-service=cockpit --permanent (optional)
------------------

*Create a blueprint called python2* adding python2 and cockpit. Then create an image based on vmdk using cockpit gui.

Also, the procedure followed con cockpit could be reproduced using the command line:

[source, bash]
------------------
# composer-cli blueprints list
# composer-cli blueprints save test (generate test.toml file)
------------------

*Add a user*

[source, bash]
------------------
[[customizations.user]]
name = "root"
description = "root user account w/ ltodemos passw"
password = "$6$BS7eu2gKUKqCmoYk$nA1b1IcqaTJLGW1ZHhumLlhBu5q69d4OeNUgtOVIqM6ah17B/g4vQT5Gggm8JiungeoHEOxODx7bAUYu1uyDH1"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHmjYFDBCrB1mgacb47t+y8UXSscnJl2WWlJluzqtInpT6At0nwqtdV3niYTHxju7e/As4MX3iwC8ubVp2DH8qXgvorDliV9SsIQTqvNKlwGkxZ5cqfYFlV4SUuS7tVTOg0yIqVSddZ2t0Sjmdp3PF7zrp6ayH7a9BBA0/8HQXU/lpdk76SGYL9L8PHOtMYnxtmr+WduoJ+X9zO9d3SUypX36NleFqhlpr1UfnSSkFO/PfRYUhry6HEmUk3Da7aS9hNS0lX/j6uf9RnSrNSzquVezyVMgsRnJ+5xr7KyhwtEig//Wr/j8TWmqvj645IWXTmj6Jw4uvi26bEORZVM5x ricardo@localhost"


[[customizations.user]]
name = "lto"
description = lto user"
password = "$6$BS7eu2gKUKqCmoYk$nA1b1IcqaTJLGW1ZHhumLlhBu5q69d4OeNUgtOVIqM6ah17B/g4vQT5Gggm8JiungeoHEOxODx7bAUYu1uyDH1"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHmjYFDBCrB1mgacb47t+y8UXSscnJl2WWlJluzqtInpT6At0nwqtdV3niYTHxju7e/As4MX3iwC8ubVp2DH8qXgvorDliV9SsIQTqvNKlwGkxZ5cqfYFlV4SUuS7tVTOg0yIqVSddZ2t0Sjmdp3PF7zrp6ayH7a9BBA0/8HQXU/lpdk76SGYL9L8PHOtMYnxtmr+WduoJ+X9zO9d3SUypX36NleFqhlpr1UfnSSkFO/PfRYUhry6HEmUk3Da7aS9hNS0lX/j6uf9RnSrNSzquVezyVMgsRnJ+5xr7KyhwtEig//Wr/j8TWmqvj645IWXTmj6Jw4uvi26bEORZVM5x ricardo@localhost"
home = "/home/lto/"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]
------------------

Use this command to create the hash for the password

[source, bash]
------------------
# python3 -c "import crypt, getpass; print(crypt.crypt(getpass.getpass(), crypt.METHOD_SHA512))"
------------------

*Push the configuration*

[source, bash]
------------------
# composer-cli blueprints push python2.toml
------------------

*Create the image*

[source, bash]
------------------
# composer-cli compose start python2 vmdk
------------------

*Check the status*

[source, bash]
------------------
# composer-cli compose status
# journalctl -fu lorax-composer (for monitoring activity)
------------------

*When Finished create the image*

[source, bash]
------------------
# composer-cli compose image UUID (taken from status)
------------------

=== Additional recommended exercises for the customer

* Create a postgresql blueprint
* From this blueprint create a vmdk image and import it on virtualbox, then start the VM

=== Post Execution

Get from customer insight and feedback of how they could use this kind of features in their day by day operation, looking for real cases to be implemented. Stimulate a conversation of max 5 minutes relating to this topic.

== CONTAINERS OCI COMPLIANT

=== Description

The docker package is replaced by the Container Tools module, which consists of Podman, Buildah, Skopeo and several other tidbits. These tools are compatible with the OCI specifications which means they can find, run, build and share containers with other tools that target the OCI standards including Docker CE, Docker EE, Kata Containers, CRI-O, and other container engines, registries, and tools. You can build with Buildah, and run with CRI-O. You can copy images from an AWS container registry to a local Podman instance. The OCI standards offer greater flexibility and choice.

=== Pre Execution

Use whiteboard to show how podman can be used instead of docker for creating, pulling and executing containers.

It's important to show the single point of failure docker daemon impone to customer and also the security issues related to the execution of containers at root level.

Talk about OCI as the foundation of having tools for working with a standard that guarantee compatibility, functioning and stability in the container world.

=== Execution

*Installation*

[source, bash]
------------------
# yum module list
# yum module install container-tools
------------------

Look at /etc/containers/registries.conf and show the registries

Registry.redhat.io, docker.io, quay.io

*Login on redhat*

[source, bash]
------------------
# podman login registry.redhat.io
------------------

*Look for nextcloud container*

[source, bash]
------------------
#podman search nextcloud
skopeo inspect docker://docker.io/library/nextcloud
------------------

*Pulling the container*

[source, bash]
------------------
# podman pull docker://docker.io/library/nextcloud
------------------

*Run the container*

[source, bash]
------------------
# podman run -d -p 8080:80 nextcloud
# Podman ps
# Podman images
------------------

*Access nextcloud http://host:8080*

Make a little tour, *create another nextcloud account* and re-access with it

*Create a container as a very basic example*

Create a Dockerfile in a folder

[source, bash]
------------------
# vim Dockerfile
FROM docker.io/library/alpine
ADD counting /usr/local/bin/counting
CMD "/usr/local/bin/counting"
------------------

*Create a basic script called counting in the folder *

[source, bash]
------------------
#vim counting

date
echo “Started"
t=1
while true; do
   echo "counting: "$t
   sleep 1
   let t=t+1
   if [[ $t -gt 9 ]]; then
      break
   fi
done
echo "Finished!"

# chmod a+x counting
# buildah bud -t counting .
# podman run counting
------------------

The script should run flawlessly

